### ISSUE TITLE
Account not updating

### ISSUE THREAD

**Issue by jokernights** [Project-Sloth/ps-banking#2]
Download release files.
Drag and drop resource into your server files.
Start resource through server.cfg.
Add the ps-banking sql file to your database.
Restart your server.

These instructions are some of the easiest I have found, but I feel there is more that needs to be done? I put it in and did remove qb-banking and the interface came up and looks beautiful but deposit / withdrawal etc it just sits at 10k and doesn't move for the account balance. I also put qb-banking back in and had both in because the instructions don't say to remove it and same thing. I also tried to replace all instances of qb-banking in all folders and still nothing. I feel there is more that needs to be done to convert over to ps-banking? what am I missing? I tried to be respectful and ask in the support discord as a genuine question but did not get a resolve.  I really like project sloth scripts and most of my server runs them. I would love to get this working as well. Thank you in advance

**Comment by MonkeyWhisper** [comment]
Is a you issue, script is working.
