### ISSUE TITLE
[Suggestion] Hints & Dead Space

### ISSUE THREAD

**Issue by rxnm** [Project-Sloth/ps-banking#3]
Hey, just been trying this out, no problems such as errors etc and everything works well, great job. 

Just some suggestions, (img1) shows all those little icons, some are self-explanatory but some you don't know what they do until clicking on them, maybe have some hints when hovering over them?

(img2) every other page bills, history, withdraw, etc makes the most of the layout, but the (overview) home page has so much dead space as shown. Maybe space it out more to fill that page?!

One more thing, you can't use ATM's without ordering of a bank card, where is that feature or is it planned? there was nothing said about it on the release page. 

![Screenshot_1](https://github.com/user-attachments/assets/f965c7d8-9f30-47fb-89b8-4df1ead00a61)
![Screenshot_2](https://github.com/user-attachments/assets/6f98d1a3-62d1-4cc0-bd29-cb1a7f6c0542)

**Comment by MonkeyWhisper** [comment]
You can send PR for that, good suggestions
