### ISSUE TITLE
[Suggestion] Add Card System

### ISSUE THREAD

**Issue by DarvinVlad** [Project-Sloth/ps-banking#33]
Add a system of cards for accessing the ATM, which are linked to the player's account (if the player loses the card, other players can use it) and add the ability to turn the function on and off.
Also, creating a PIN code for the card and changing it at the bank, blocking the card, re-issuing and the ability to issue a credit card (as an idea)

**Comment by MonkeyWhisper** [comment]
Great, do it yourself.
